Update pom.xml
jacoco version upgrade from 0.7.2.201409121644 to 0.8.2 lines 80 and 310
Exception: java.lang.NoSuchFieldException: $jacocoAccess ==> https://github.com/vaskoz/core-java9-impatient/issues/11